name: $(SourceBranchName)-$(Date:yyyy.MM.dd)$(Rev:.r)

trigger:
  tags:
    include:
    - v*
  branches:
    exclude:
    - master  

pr: none

pool:
  vmImage: ubuntu-16.04

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: sed -i 's/place_key_here/$(apikey)/' apikey.js
    workingDirectory: '$(Build.SourcesDirectory)/public'
  displayName: 'API key insertion'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script:
      docker run --rm -i 
      --env-file <(env | grep -vE 'r|n' | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') 
      --env ELECTRON_CACHE="/root/.cache/electron" 
      --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" 
      -v ${PWD}:/project 
      -v ${PWD##*/}-node-modules:/project/node_modules 
      -v ~/.cache/electron:/root/.cache/electron 
      -v ~/.cache/electron-builder:/root/.cache/electron-builder 
      electronuserland/builder:wine 
      /bin/bash -c "yarn && yarn dist"
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Build and create dist archives'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cp dist/*.zip $(Build.ArtifactStagingDirectory)'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Move built files'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'awk -v N=2 ''/## v/&&--N<=0{exit}{print}'' changelog.md > $(Build.ArtifactStagingDirectory)/notes'
    workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Changelog'

- task: GitHubRelease@0
  displayName: 'GitHub release'
  inputs:
    gitHubConnection: 'github connection 1'
    repositoryName: 'Dixaba/TurboAery'
    releaseNotesFile: '$(Build.ArtifactStagingDirectory)/notes'
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
    addChangeLog: false
